# -*- coding: utf-8 -*-
"""Console.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UPV5B0v7kbQsrqmGIjR5N3PCsp_Btyub
"""

import joblib
import pandas as pd


model = joblib.load('/content/svm_heart_disease_model.pkl')
scaler = joblib.load('/content/scaler.pkl')
feature_columns = joblib.load('/content/feature_columns.pkl')


def input_int(prompt, min_val=None, max_val=None):
    while True:
        try:
            value = int(input(prompt))
            if min_val is not None and value < min_val:
                raise ValueError
            if max_val is not None and value > max_val:
                raise ValueError
            return value
        except ValueError:
            print(f"Введіть ціле число в діапазоні [{min_val}, {max_val}]")


def input_float(prompt, min_val=None, max_val=None):
    while True:
        try:
            value = float(input(prompt))
            if min_val is not None and value < min_val:
                raise ValueError
            if max_val is not None and value > max_val:
                raise ValueError
            return value
        except ValueError:
            print("Введіть коректне числове значення")


def input_choice(prompt, choices):
    choices_lower = [c.lower() for c in choices]
    while True:
        value = input(prompt).strip().lower()
        if value in choices_lower:
            return choices[choices_lower.index(value)]
        print(f"Дозволені значення: {', '.join(choices)}")


def get_user_input():
    print("\nВведіть клінічні показники пацієнта:\n")

    data = {
        "age": input_int("Вік (18–100): ", 18, 100),
        "sex": input_choice("Стать (Male/Female): ", ["Male", "Female"]),
        "trestbps": input_float("Артеріальний тиск (80–200 мм рт. ст.): ", 80, 200),
        "chol": input_float("Холестерин (100–600 mg/dl): ", 100, 600),
        "fbs": input_choice("Цукор >120 mg/dl (True/False): ", ["True", "False"]),
        "thalch": input_float("Максимальний пульс (60–220): ", 60, 220),
        "exang": input_choice("Стенокардія при навантаженні (True/False): ", ["True", "False"]),
        "oldpeak": input_float("ST-депресія (0.0–6.5): ", 0.0, 6.5),
        "cp": input_choice(
            "Тип болю (typical angina / atypical angina / non-anginal / asymptomatic): ",
            ["typical angina", "atypical angina", "non-anginal", "asymptomatic"]
        ),
        "restecg": input_choice(
            "ЕКГ (normal / stt abnormality / lv hypertrophy): ",
            ["normal", "stt abnormality", "lv hypertrophy"]
        ),
        "slope": input_choice(
            "Нахил ST (upsloping / flat / downsloping): ",
            ["upsloping", "flat", "downsloping"]
        ),
        "thal": input_choice(
            "Thal (normal / fixed defect / reversable defect): ",
            ["normal", "fixed defect", "reversable defect"]
        ),
        "ca": input_int("Кількість судин (0–3): ", 0, 3)
    }

    return pd.DataFrame([data])


def preprocess_input(df):
    df_encoded = pd.get_dummies(df)

    for col in feature_columns:
        if col not in df_encoded.columns:
            df_encoded[col] = 0

    df_encoded = df_encoded[feature_columns]
    return scaler.transform(df_encoded)


def make_prediction():
    user_df = get_user_input()
    X_processed = preprocess_input(user_df)

    prediction = model.predict(X_processed)[0]
    probability = model.predict_proba(X_processed)[0, 1]

    risk = "ВИСОКИЙ" if prediction == 1 else "НИЗЬКИЙ"

    print("РЕЗУЛЬТАТ ПРОГНОЗУ")
    print(f"Ризик серцево-судинного захворювання: {risk}")
    print(f"Ймовірність наявності ССЗ: {probability:.2%}")


def main_menu():
    while True:
        print("Оберіть дію:")
        print("1 — Отримати прогноз")
        print("0 — Вийти")

        choice = input("Ваш вибір: ").strip()

        if choice == "1":
            make_prediction()
        elif choice == "0":
            print("Завершення роботи!")
            break
        else:
            print("Невірний вибір. Спробуйте ще раз.\n")


if __name__ == "__main__":
    main_menu()